config/routes.rb
Glowcon::Application.routes.draw do

  devise_for :users, 
    path: '', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout'},
    controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks"
    }
  
  #devise_scope :user do
   # get 'confirm/:confirmation_token', to: 'users/confirmations#show'
  #end 
  
  resources :entries, only: [:show, :index]

  get '/archive/:month', to: 'entries#index', as: 'archive_entries'
  get '/category/:category', to: 'entries#index', as: 'category_entries'

  resources :users do
    member do
      get :following, :followers
      get :load_follows
    end
    
    collection do
      get :pitching
      post :final_step
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :email_validation

  resources :companies do
    put :update_pitch
    put :change_logo
    resources :microposts, only: [ :create, :destroy ] do
      get :load, on: :collection
    end
    resources :messages, only: [ :create ]
  end

  resources :microposts, only: [] do
    resources :comments, only: [ :create, :destroy ]
  end

  resources :contacts, only: [:new, :create]

  resources :messages, only: [ :index ] do
    collection do
      get :search
      get :load
      post :mass_sending
    end
  end

  resources :connections, only: [ :index ] do
    collection do
      get :follow
      get :load
    end
  end

  resources :tags, only: [] do
    collection do
      get :autocomplete
    end
  end

  resources :countries, only: [ :index ], controller: :location_autocomplete do
    get :states
  end

  resources :profile, only: [ :update ] do
    member do
      patch :update_pitch
      patch :change_logo
      patch :update_user_data
    end
  end

  root to: 'home#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/dashboard', to: 'static_pages#dashboard'
  get '/terms', to: 'static_pages#terms'
  get '/code', to: 'static_pages#code'
  get '/walk', to: 'static_pages#walk'

  get 'static_pages/final_step_design'
  get 'static_pages/create_glows'
  get 'static_pages/make_connections'
  get 'static_pages/private_messages'

  resources :m do
    collection do
      get :connections
      get :welcome
      get :dashboard
      get :home
      get :blog
      get :blog_item
      get :contacts
      get :reset
      get :sign_1
      get :sign_2
      get :sign_3
      get :profile
      get :messages
      get :followers
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @company = current_user.company
      render template: 'static_pages/home_for_signed'
    else
      @active_tab = 'home'
      @tags = ActsAsTaggableOn::Tag.joins(:taggings).
        select("tags.name, tags.capabilities_offered_count").distinct.
        where('taggings.context = ?', 'capabilities_offered').
        order('capabilities_offered_count ASC').
        limit(30)

      render template: 'static_pages/home_for_unsigned'
    end
  end

  def dashboard
    return redirect_to signin_path unless signed_in?

    @micropost  = current_user.microposts.build
    @feed_items = current_user.feed.page(params[:page])

    @active_tab = 'dashboard'
  end

  def help
    @active_tab = 'help'
  end

  def about
    @active_tab = 'about'
  end

  def contact
    @active_tab = 'contact'
  end

  def final_step_design
    render layout: 'separate_header'
  end

  def create_glows
  end

  def make_connections
  end

  def private_messages
  end

  def terms
  end

  def code
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_glows_feed.html.haml
.b-feeds__container
  / ====== A GLOW WITH COMMENT =======
  .b-feed__item.clearfix
    = image_tag 'sample/ava.png', class: 'b-feed__avatar'
    .b-feed__comment
      %a.b-feed__author{href: '#'} Nick Mayburg
      %p.b-feed__comment-text
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.
      .b-feed__actions
        %a{href: '#'} Comment
        %a{href: '#'} Delete
        %span.b-feed__timestamp 2 days ago
    .b-feed__subitem.clearfix
      = image_tag 'sample/ava.png', class: 'b-feed__avatar'
      .b-feed__comment
        %a.b-feed__author{href: '#'} Nick Mayburg
        %p.b-feed__comment-text
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.
        .b-feed__actions
          %span.b-feed__timestamp 2 days ago
    .b-feed__add-comment
      %input.fullwidth{type: 'text', placeholder: 'Write a comment...'}
  / ====== A GLOW WITHOUT COMMENT =======
  .b-feed__item.clearfix
    = image_tag 'sample/ava.png', class: 'b-feed__avatar'
    .b-feed__comment
      %a.b-feed__author{href: '#'} Nick Mayburg
      %p.b-feed__comment-text
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.
      .b-feed__actions
        %span.b-feed__timestamp 2 days ago
    .b-feed__add-comment
      %input.fullwidth{type: 'text', placeholder: 'Write a comment...'}

  - 6.times do
    .b-feed__item.clearfix
      = image_tag 'sample/ava.png', class: 'b-feed__avatar'
      .b-feed__comment
        %a.b-feed__author{href: '#'} Nick Mayburg
        %p.b-feed__comment-text
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.
        .b-feed__actions
          %span.b-feed__timestamp 2 days ago

app/views/static_pages/_intelligence.html.haml
.b-intelligence.pull-left
  %h3.c-blue
    Actionable marketing Intelligence
  .b-intelligence__items-container
    .b-intelligence__item
      %a.b-intelligence__item-title{href: '#'}
        120
      %p.b-intelligence__item-description
        Companies are currently looking for capabilities your company offers.
    .b-intelligence__item
      %a.b-intelligence__item-title{href: '#'}
        80
      %p.b-intelligence__item-description
        Companies offer capabilities your company is looking for.
    .b-intelligence__item
      %a.b-intelligence__item-title{href: '#'}
        Network Security
      %p.b-intelligence__item-description
        Companies are currently looking for capabilities your company offers.
    .b-intelligence__item
      %a.b-intelligence__item-title{href: '#'}
        Rails
      %p.b-intelligence__item-description
        Companies offer capabilities your company is looking for.
    .b-intelligence__item
      %a.b-intelligence__item-title{href: '#'}
        25
      %p.b-intelligence__item-description
        Companies are currently looking for capabilities your company offers.
    .b-intelligence__item
      %a.b-intelligence__item-title{href: '#'}
        10
      %p.b-intelligence__item-description
        Companies offer capabilities your company is looking for.

  .b-intelligence__wanted.pull-left
    %h4.c-blue
      Top Capabilities wanted right now
    .b-intelligence__labels
      .labels-row
        .s-label{style: "width: 100%;"}
          %span.s-label__text
            Software development
          %span.s-label__number
            254
      .labels-row
        .s-label.pull-left{style: "width: 154px;"}
          %span.s-label__text
            Scrum
          %span.s-label__number
            253
        .s-label.pull-right{style: "width: 108px;"}
          %span.s-label__text
            Rails
          %span.s-label__number
            72

  .b-intelligence__needed.pull-right
    %h4.c-blue
      Top Capabilities wanted right now
    .b-intelligence__labels
      .labels-row
        .s-label{style: "width: 100%;"}
          %span.s-label__text
            Software development
          %span.s-label__number
            254
      .labels-row
        .s-label.pull-left{style: "width: 154px;"}
          %span.s-label__text
            Scrum
          %span.s-label__number
            253
        .s-label.pull-right{style: "width: 108px;"}
          %span.s-label__text
            Rails
          %span.s-label__number
            72

  .b-intelligence__companies-container
    .b-intelligence__companies
      %h4.c-blue Companies we found
      %h4.c-blue Companies That found us
    .b-intelligence__companies
      %span 234
      %span 1024

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')

- description = "This is the about page for #{link_to 'Glowfori', 'http://www.glowfori.com', class: 'standart_link'}".html_safe

.c-content
  = render 'm/shared/page_title', title: 'About Us', description: description
.b-blog
  .c-content.static_page
    %p

app/views/static_pages/code.html.haml
- provide(:title, 'Code of Conduct')

.c-content
  = render 'm/shared/page_title', title: 'Code of Conduct', description: ''
.b-blog
  .c-content.static_page.code_of_conduct
    %p
      Welcome to
      %a{href: "http://glowfori.com"} 
        glowfori.com 
      a website and service owned and operated by Glowfori S.A.(
      %strong
        "[ Glowfori ]"
      ). 
      We are registered in Switzerland and have our registered office at Chemin Des Voiron 9, 1296-Coppet. 
    %p  
      The core principle of Glowfori is to create and maintain a 
      %strong
        Trusted Network 
      of companies around the world.   
      The integrity of the Glowfori global network is therefore a product of the conduct of each individual company member.   
      We take member conduct on the Site seriously and ask all members to work collectively to uphold the standards and integrity of the Glowfori community.  
      This document provides guidance on expected member conduct as well as guidance on your role as a member in the Glowfori community.

    %ul.main_nav_ul
      %li.main_code_nav
        %h3 1. Purpose
        %p 
          The Glowfori Code of Conduct sets out the expected professional standards and business ethics required by members of participating companies in the Glowfori community as a condition of membership.  
          This Code of Conduct applies to all members, irrespective of their membership grade, the role they fulfil, or the jurisdiction where they are employed or discharge their contractual obligations.  It governs the conduct of the individual representing their respective company, not the nature of the business or ethics of any Relevant Authority. 

        %b.terms_bold
          The term “Relevant Authority” in this document is used to identify the person(s) or organisation(s) which has / have authority over the activity of individuals in their professional capacity. For subscribed Glowfori members this is normally an employer. 

        %p 
          Members are expected to exercise their own judgement (which should be made in such a way as to be reasonably justified) to meet the requirements of the code and seek advice if in doubt.  
          Questions about the Code of Conduct can be directed to #{mail_to("tc@glowfori.com")}.

      %li.main_code_nav
        %h3 2. General Guidelines
        %p
          The Code of Conduct sets out certain, basic principles that are intended to help members maintain the highest standards of professional conduct. 
          Should a case arise where a member is believed to have fallen short of the standards desired, members are expected to notify Glowfori by email at #{mail_to("tc@glowfori.com")}.

      %li.main_code_nav
        %h3 3. Breaches 
        %p
          If a member should know of, or become aware of, any breach of this Code of Conduct by another member they are expected to notify Glowfori by email to address: #{mail_to("tc@glowfori.com")}.

        %p   
          Any breach of the Code of Conduct brought to the attention of Glowfori, or of which Glowfori becomes aware, will be investigated by the Site’s Administrators.  
          The Site Administrators may exercise, at their discretion, the appropriate remedial action which may include deletion of the offending members account. 
        %p
          Where Glowfori  receives information that a member has been convicted of a criminal offence, the member, when asked will provide a Standard Disclosure Certificate or other similar notice providing evidence of their criminal record (if any) within 28 days. 
          Note that not all convictions are seen as relevant to membership in Glowfori  and each case will be considered individually.

      %li.main_code_nav
        %h3 4. Member Commitments
        %p 
          The following list of member commitments are intended as guidance and do not represent an exhaustive list.

      %li.main_code_nav
        %h3 4.1. Company Representations  
        %p
          Members will:
        %ul
          %li.circle_list  
            %p 
              Create truthful and accurate company profiles which provides a true representation of the capabilities, experience and accreditations of the company
          %li.circle_list
            %p
              Post capabilities being sought from other members which are legitimate, truthful, current and accurate
          %li.circle_list
            %p
              Maintain the company profiles such that they remain a current and true representation of the company

      %li.main_code_nav
        %h3 4.2. Member Communications
        %p Members will:
        %ul
          %li.circle_list
            %p 
              Contact members for the purpose of legitimate business opportunities
          %li.circle_list
            %p 
              Follow members, (Which includes distribution of information or requirements),  for legitimate and current business needs
          %li.circle_list
            %p 
              Exercise discretion when posting “public” messages to ensure they are for legitimate business needs and / or in the interest of the Glowfori community
          %li.circle_list
            %p 
              Ensure all “private” messages are treated with discretion and only used for the purposes of conducting legitimate business between members of the community

      %li.main_code_nav
        %h3 4.3. Member Transactions
        %p Members will:
        %ul
          %li.circle_list
            %p 
              Respond to member messages, queries and requests honestly and in a timely manner
          %li.circle_list
            %p 
              Only make commitments to other members in good faith 
          %li.circle_list
            %p 
              Fulfil all obligations committed to other members to the best of their ability 
          %li.circle_list
            %p 
              Fulfil all obligations in a timely manner
          %li.circle_list
            %p 
              Provide timely and honest information regarding to progress on commitments to other members

      %li.main_code_nav
        %h3 4.4. Glowfori Community Interests
        %p
          Members will:
        %ul
          %li.circle_list
            %p 
              Report any suspected breaches to #{mail_to("tc@glowfori.com")}.
          %li.circle_list
            %p 
              Conduct themselves at all times in the interest of the Glowfori community

      %li.main_code_nav
        %h3 5. Contact us
        %p
          Correspondence in connection with this Code of Conduct should be directed to: #{mail_to("tc@glowfori.com")}.

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:page_heading, 'Contact') %>
<div class="spacer"></div>
<div class="row">
  <div class="span8 offset2 center">
    <p class="em1-2 white">
      If you have any questions, don't hesitate to get in touch.
    </p>
    <br/><br/>
  </div>
</div>

app/views/static_pages/dashboard.html.erb
<%= provide(:title, 'Dashboard') %>
<%= provide(:page_heading, 'Dashboard') %>

<div class="row">
  <%= link_to "Create Glows", company_glows_url(current_user.company) %>
  <%= link_to "Make Connections", connections_url %>
  <%= link_to "Get Found", messages_url %>
</div>

app/views/static_pages/final_step_design.html.haml
- provide(:title, 'Welcome')
- content_for :page_heading do
  .company-welcome
    Welcome
    %span ACME
.s-white-bg.pull-up.relative
  .container
    %ul.row
      %li.span4.center
        = link_to 'Create glows', '#'
      %li.span4.center
        = link_to 'Make connections', '#'
      %li.span4.center
        = link_to 'Get found @ glow', '#'
.container.b-final-step
  .row
    .span4.center
      %p.large-text
        Start following companies
        and share public or private
        messages in your network.
      %p.small-text
        Use your Glows to share knowledge,
        Find leads, share services, ideas,
        products and innovations.
      = link_to "Let's go", '#', class: 'btn btn-primary btn-huge'


    .span4.center
      %p.large-text
        You told us what you were
        looking for. On your home
        page we found all the
        companies that offer what
        you are looking for.
      %p.small-text
        Start following these companies,
        Share a glow or connect privately.
      = link_to "Let's go", '#', class: 'btn btn-primary btn-huge'

    .span4.center
      %p.large-text
        To be found you have to be
        known. Glowfori operates on
        Matching needs with
        capabilities. Hone your data
        skills by continuously
        reviewing the capabilities
        you offer.
      %p.small-text
        We have written a small guide to help you
        become the best at  representing
        your companies  capabilities.
      = link_to "Let's go", '#', class: 'btn btn-primary btn-huge'

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<% provide(:page_heading, 'Help') %>
<div class="spacer"></div>
    <p>
      Get help somewhere
    </p>

app/views/static_pages/home_for_signed.html.haml
- provide(:title, 'Welcome')
.c-content
  = render 'layout_components/company_info', name: @company.company_name, title: 'Welcome'
.b-welcome
  .b-welcome__header
    .c-content
      = link_to 'Get Found', company_path(@company), class: 'b-welcome__header-title'
      = link_to 'Find Companies', connections_path, class: 'b-welcome__header-title'
      = link_to 'Start Glowing', companies_path, class: 'b-welcome__header-title'
  .c-content
    %table.b-welcome__columns
      %tr
        %td.b-welcome__column
          %p
            Your company profile page is the key to being discovered by other
            <strong class=highlighted>glowfori</strong> members. The more you tell us about you company the more we
            can match you with other community members.
        %td.b-welcome__column
          %p
            Search for other <strong class=highlighted>glowfori</strong> members based on their capabilities, location,
            and objectives. Explore the community and make your own connections.
        %td.b-welcome__column
          %p
            Glows are messages between members. They can be private conversations, messages to yor followers or public
            broadcasts. Start interacting with other <strong class=highlighted>glowfori</strong> members.
      %tr
        %td.b-welcome__column.center= link_to 'LET\'S GO', company_path(@company), class: 's-btn-warning'
        %td.b-welcome__column.center= link_to 'LET\'S GO', connections_path, class: 's-btn-warning'
        %td.b-welcome__column.center= link_to 'LET\'S GO', companies_path, class: 's-btn-warning'

app/views/static_pages/home_for_unsigned.html.haml
.b-home
  .b-home__logo
    = link_to '', root_url, class: 'b-logo-big'
  %h1.b-home__slogan
    Home to the connected companies.
    %br
    Finding trusted quality partners the first time.
  .b-home__auth
    = link_to 'Sign up Now', signup_path, class: 's-btn-warning'
  .b-home__tour Take a Tour

  .b-home__row
    .b-home__form.sign_in
      .s-rounded-box
        %h2.s-header Please enter your details
        = render 'sessions/form'

    .b-home__tags
      .s-rounded-box
        %h2.s-header Available Today on Glowfori
        .s-tags
          - @tags.each_slice(4).each_with_index do |tags_block, index|
            - tags_block.each do |tag|
              = link_to tag.name, companies_url(by_tags: tag.name), class: "s-tags__tag #{tag_css_class(index)}"

= content_for(:javascript_code) do
  HomePage.init();

app/views/static_pages/make_connections.html.haml
- provide(:title, 'Welcome')
- content_for :page_heading do
  .company-welcome
    Peter @
    %span ACME
%br/
.row
  %h3.t-title
    Elevator Pitch / Edit by changing text

.b-connections
  .row
    .b-message-textbox.pull-left.clearfix
      %form.new_micropost.s-ta-single
        .field
          %textarea#micropost_content.fullwidth{:name => "micropost[content]", :placeholder => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.", :rows => "8"}
        .button-container.pull-right
          %span.countdown 140 characters remaining
          %input.btn.btn-primary{:name => "commit", :type => "submit", :value => "Post"}
    .b-message-textbox.pull-right.clearfix
      %form.new_micropost.s-ta-single
        .field
          %textarea#micropost_content.fullwidth{:name => "micropost[content]", :placeholder => "Share a Glow with your followers", :rows => "8"}
        .button-container.pull-right
          %span.countdown 140 characters remaining
          %input.btn.btn-primary{:name => "commit", :type => "submit", :value => "Post"}
  .row
    = render 'intelligence'

    .b-feed.pull-right
      %h3 Glows feed
      = render 'glows_feed'

app/views/static_pages/private_messages.html.haml
- provide(:title, 'Welcome')
- content_for :page_heading do
  .company-welcome
    Peter @
    %span ACME


.s-table
  .s-table__sidebar
  .s-table__header
    %table
      %thead
        %tr
          %th{style: "width:250px" } Company Name
          %th{style: "width:170px" } Offers
          %th{style: "width:90px" } City
          %th{style: "width:80px" } Country
          %th Select
  .s-table__content
    %table
      %tbody
        %tr
          %td.b-table__company-name
            .name ACME
            .title 250 Char of pitch text
          %td{style: "width:170px" }
            .b-table__tags A list of tags and skills
          %td{style: "width:90px" }
            .b-table__city Copenhagen
          %td{style: "width:80px" }
            .b-table__country Denmark
          %td.b-table__checkbox

        %tr.active
          %td.b-table__company-name
            .name ACME
            .title 250 Char of pitch text
          %td
            .b-table__tags A list of tags and skills
          %td
            .b-table__city CopenhagenCopenhagen
          %td
            .b-table__country DenmarkDenmark
          %td.b-table__checkbox
        %tr
          %td.b-table__company-name
            .name ACME
            .title 250 Char of pitch text
          %td
            .b-table__tags A list of tags and skills
          %td
            .b-table__city Copenhagen Copenhagen
          %td
            .b-table__country Denmark Denmark
          %td.b-table__checkbox


.b-connections
  .row.nomargin
    .b-message-textbox.pull-left.clearfix
      %form.new_micropost.s-ta-single
        .field
          %textarea#micropost_content.fullwidth{:name => "micropost[content]", :placeholder => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.", :rows => "8"}
        .button-container.pull-right
          %span.countdown 140 characters remaining
          %input.btn.btn-primary{:name => "commit", :type => "submit", :value => "Post"}

app/views/static_pages/walk.html.haml
- provide(:title, 'Walk through demo')