config/routes.rb
Glowcon::Application.routes.draw do

  devise_for :users, 
    path: '', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout'},
    controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks"
    }
  
  #devise_scope :user do
   # get 'confirm/:confirmation_token', to: 'users/confirmations#show'
  #end 
  
  resources :entries, only: [:show, :index]

  get '/archive/:month', to: 'entries#index', as: 'archive_entries'
  get '/category/:category', to: 'entries#index', as: 'category_entries'

  resources :users do
    member do
      get :following, :followers
      get :load_follows
    end
    
    collection do
      get :pitching
      post :final_step
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :email_validation

  resources :companies do
    put :update_pitch
    put :change_logo
    resources :microposts, only: [ :create, :destroy ] do
      get :load, on: :collection
    end
    resources :messages, only: [ :create ]
  end

  resources :microposts, only: [] do
    resources :comments, only: [ :create, :destroy ]
  end

  resources :contacts, only: [:new, :create]

  resources :messages, only: [ :index ] do
    collection do
      get :search
      get :load
      post :mass_sending
    end
  end

  resources :connections, only: [ :index ] do
    collection do
      get :follow
      get :load
    end
  end

  resources :tags, only: [] do
    collection do
      get :autocomplete
    end
  end

  resources :countries, only: [ :index ], controller: :location_autocomplete do
    get :states
  end

  resources :profile, only: [ :update ] do
    member do
      patch :update_pitch
      patch :change_logo
      patch :update_user_data
    end
  end

  root to: 'home#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/dashboard', to: 'static_pages#dashboard'
  get '/terms', to: 'static_pages#terms'
  get '/code', to: 'static_pages#code'
  get '/walk', to: 'static_pages#walk'

  get 'static_pages/final_step_design'
  get 'static_pages/create_glows'
  get 'static_pages/make_connections'
  get 'static_pages/private_messages'

  resources :m do
    collection do
      get :connections
      get :welcome
      get :dashboard
      get :home
      get :blog
      get :blog_item
      get :contacts
      get :reset
      get :sign_1
      get :sign_2
      get :sign_3
      get :profile
      get :messages
      get :followers
    end
  end
end

app/controllers/messages_controller.rb
require 'company_modules/search'

class MessagesController < ApplicationController

  include CompanyModules::Search

  before_action :authenticate_user!
  before_action :set_active_tab!, only: [ :index ]
  before_action :search_by_conditions, only: [ :index, :search, :load ]
  before_action :set_company, only: [ :create ]

  def index
  end

  def create
    if params[:micropost][:content].present?
      @message = current_user.microposts.create!(
        message_params.merge!(
          to: @company.user,
          :private => true
        )
      )
    end
  end

  def mass_sending
    @company_ids = params[:recepients].split(',') if params[:recepients].present?
    @message = message_params[:content] if message_params.present?

    if @company_ids.present? && @company_ids.count < 6 && @message.present?
      @company_ids.each do |company_id|
        company = Company.find(company_id)

        current_user.microposts.create!(
          message_params.merge!(
            to: company.user,
            :private => true
          )
        )
      end
    end
  end

  def load
  end

  def search
  end

  private

  def set_active_tab!
    @active_tab = 'messages'
  end

  def set_company
    @company = Company.verified.find(params[:company_id])
  end  

  def message_params
    params.require(:micropost).permit(:company_id, :user_id, :content)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= form_for Micropost.new, url: company_messages_path(@company), remote: true, html: { class: 'b-post-form' } do |f|
  .s-textarea
    = f.text_area :content, class: 'micropost_content', placeholder: "Leave a private Glow message for #{@company.company_name}.", rows: "7"
  .b-post-form__tools
    = render 'messages/status_messages'
    .b-post-form__hint.countdown.share_glow_count 140 characters remaining
    = f.submit 'POST', class: 's-btn btn'
    = image_tag 'spinner.gif', class: 'loading_spinner' 

app/views/messages/_group_message_form.html.haml
= form_for Micropost.new, url: mass_sending_messages_url, remote: true, html: { class: 'b-post-form mass_sending_form' } do |f|
  = hidden_field_tag :recepients
  .s-textarea
    = f.text_area :content, class: 'micropost_content', placeholder: "Post a Glow to the companies you would like to partner with (max 5)", rows: "3"
  .b-post-form__tools
    .b-post-form__hint.countdown.share_glow_count 140 characters remaining
    = f.submit 'POST', class: 's-btn'
    = image_tag 'spinner.gif', class: 'loading_spinner pull-right' 

app/views/messages/_loading_spinner.html.haml
.companies_loading_spinner.pull-right
  = image_tag 'spinner.gif'
  %span
    Loading ...

app/views/messages/_search_box.html.haml
.c-content.search_company_block
  = form_tag search_messages_url, remote: true, method: :get, class: 's-form search_by_companies' do
    = hidden_field_tag :next_page, @companies.total_pages > @companies.current_page ? @companies.current_page + 1 : 0
    = hidden_field_tag :search_by_tags_mode, params[:search_by_tags_mode].present? ? params[:search_by_tags_mode] : 'offer_tags'
   
    .pull-left.left_side
      .s-form__group
        = label_tag :by_tags, 'By Tags'
        .s-inline-input.tag_autocomplete_block
          = hidden_field_tag :by_tags, params[:by_tags].to_s.split('_').join(',')
          %ul.tag_variants#by_tags_block

    .pull-left.right_side  
      .s-form__group
        = label_tag :by_name, 'By Name'
        .s-inline-input.company_by_name_field
          = text_field_tag :by_name, nil, placeholder: 'apple'
        
        .pull-left
          = label_tag :by_country, 'By Country'
          .s-inline-input.small
            = text_field_tag :by_country, nil, class: 'hidden', id: "company_country_id"
            = text_field_tag :country_id, nil, placeholder: 'Ex: United States', autocomplete: :off

        .pull-left
          = label_tag :by_state_id, 'By State'
          .s-inline-input.small
            = text_field_tag :by_state, nil, class: 'hidden', id: "company_state_id"
            = text_field_tag :state_id, nil, placeholder: 'Ex: Nebraska', autocomplete: :off
        
        .pull-left
          = label_tag :by_city, 'By City'
          .s-inline-input.small
            = text_field_tag :by_city, nil, placeholder: 'Ex:New York', autocomplete: :off   

        = submit_tag 'Search', class: 's-btn pull-right'

app/views/messages/_search_tags_filter.html.haml
= select_tag :tags_search_mode, options_for_select([ ['by offer tags', 'offer_tags'], ['by looked tags', 'looked_tags'], ['by certificates', 'certificates'] ],selected: "#{params[:search_by_tags_mode].present? ? params[:search_by_tags_mode] : 'offer_tags' }"), class: 'companies_search_filter'

app/views/messages/_status_messages.html.haml
.errors_block
  .group_message_error You can only post to 5 companies at the same time!
  .group_message_no_companies_error You should select at least one company (max 5)!
  .group_message_no_message_error You can't compose blank Glow!
  .group_message_success Sent successfully!

app/views/messages/_table.html.haml
.s-table__content.scroll-pane
  %table
    %tbody
      - if @companies.blank?
        %p.s-table.company_table
          No companies found.
      - @companies.each do |company|
        = render 'messages/table_item', company: company

app/views/messages/_table_header.html.haml
.s-table__header
  %table
    %thead
      %tr
        %th{style: "width:250px" } Company Name
        %th.search_filter
          = render 'messages/search_tags_filter'
        %th{style: "width:90px" } City
        %th{style: "width:80px" } Country
        %th Select

app/views/messages/_table_item.html.haml
%tr{ id: dom_id(company) }
  %td.b-table__company-name
    .name
      = truncate(company.company_name, length: 40)
    .title
      = truncate(company.company_profile, length: 240)
    = link_to '', company_path(company), class: 'company_details_link'
  %td{style: "width:170px" }
    .b-table__tags
      = tags_list(company, params[:search_by_tags_mode])
  %td{style: "width:90px" }
    .b-table__city
      = company.addresses.first.city if company.addresses.first.present?
  %td{style: "width:80px" }
    .b-table__country
      = company.addresses.first.country.try(:name) if company.addresses.first.present?
  %td.b-table__checkbox

app/views/messages/_table_sidebar.html.haml
.s-table__sidebar

app/views/messages/create.js.erb
$( '#new_micropost' ).find( '.btn' ).show();
$( '#new_micropost' ).find( '.loading_spinner' ).hide();

Messages.select_and_show(<%= @message.blank? %>, true);

app/views/messages/load.js.erb
<% @companies.each do |company| %>
  $('tbody').append("<%= escape_javascript(render(
	  'messages/table_item', 
	  company: company
  )) %>");
<% end %>

Messages.set_next_pagination_step("<%= @companies.total_pages > @companies.current_page ? @companies.current_page + 1 : 0 %>");
Messages.refreshNav();

app/views/messages/mass_sending.js.erb
$( '#new_micropost' ).find( '.s-btn' ).show();
$( '#new_micropost' ).find( '.loading_spinner' ).hide();

<% if @company_ids.blank? %>
  $( '.group_message_no_companies_error' ).show();
<% elsif @company_ids.count > 5 %>
  $( '.group_message_error' ).show();
<% else %>
  Messages.select_and_show(<%= @message.blank? %>);
<% end %>

app/views/messages/search.js.erb
$( '.companies_container' ).html("<%= escape_javascript(render(
  'messages/table'
)) %>");

Messages.js_scroll_bar_init();
Messages.set_next_pagination_step("<%= @companies.total_pages > @companies.current_page ? @companies.current_page + 1 : 0 %>");
Messages.auto_loading_companies_on_scroll_to_the_bottom();
Messages.correct_height_for_container("<%= @companies.length %>");