config/routes.rb
Glowcon::Application.routes.draw do

  devise_for :users, 
    path: '', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout'},
    controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks"
    }
  
  #devise_scope :user do
   # get 'confirm/:confirmation_token', to: 'users/confirmations#show'
  #end 
  
  resources :entries, only: [:show, :index]

  get '/archive/:month', to: 'entries#index', as: 'archive_entries'
  get '/category/:category', to: 'entries#index', as: 'category_entries'

  resources :users do
    member do
      get :following, :followers
      get :load_follows
    end
    
    collection do
      get :pitching
      post :final_step
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :email_validation

  resources :companies do
    put :update_pitch
    put :change_logo
    resources :microposts, only: [ :create, :destroy ] do
      get :load, on: :collection
    end
    resources :messages, only: [ :create ]
  end

  resources :microposts, only: [] do
    resources :comments, only: [ :create, :destroy ]
  end

  resources :contacts, only: [:new, :create]

  resources :messages, only: [ :index ] do
    collection do
      get :search
      get :load
      post :mass_sending
    end
  end

  resources :connections, only: [ :index ] do
    collection do
      get :follow
      get :load
    end
  end

  resources :tags, only: [] do
    collection do
      get :autocomplete
    end
  end

  resources :countries, only: [ :index ], controller: :location_autocomplete do
    get :states
  end

  resources :profile, only: [ :update ] do
    member do
      patch :update_pitch
      patch :change_logo
      patch :update_user_data
    end
  end

  root to: 'home#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/dashboard', to: 'static_pages#dashboard'
  get '/terms', to: 'static_pages#terms'
  get '/code', to: 'static_pages#code'
  get '/walk', to: 'static_pages#walk'

  get 'static_pages/final_step_design'
  get 'static_pages/create_glows'
  get 'static_pages/make_connections'
  get 'static_pages/private_messages'

  resources :m do
    collection do
      get :connections
      get :welcome
      get :dashboard
      get :home
      get :blog
      get :blog_item
      get :contacts
      get :reset
      get :sign_1
      get :sign_2
      get :sign_3
      get :profile
      get :messages
      get :followers
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      @company = current_user.company
      render template: 'home/home_for_signed'
    else
      @active_tab = 'home'
      @tags = ActsAsTaggableOn::Tag.joins(:taggings).
        select("tags.name, tags.capabilities_offered_count").distinct.
        where('taggings.context = ?', 'capabilities_offered').
        order('capabilities_offered_count ASC').
        limit(30)

      render template: 'home/home_for_unsigned'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home_for_signed.html.haml
- provide(:title, 'Welcome')
.c-content
  = render 'layout_components/company_info', name: @company.company_name
.b-welcome
  .b-welcome__header
    .c-content
      = link_to 'Get Found', connections_path, class: 'b-welcome__header-title'
      = link_to 'Find Companies', companies_path, class: 'b-welcome__header-title'
      = link_to 'Start Glowing', company_path(@company), class: 'b-welcome__header-title'
  .c-content
    %table.b-welcome__columns
      %tr
        %td.b-welcome__column
          %p
            Your company profile page is the key to being discovered by other
            <strong class=highlighted>glowfori</strong> members. The more you tell us about you company the more we
            can match you with other community members.
        %td.b-welcome__column
          %p
            Search for other <strong class=highlighted>glowfori</strong> members based on their capabilities, location,
            and objectives. Explore the community and make your own connections.
        %td.b-welcome__column
          %p
            Glows are messages between members. They can be private conversations, messages to yor followers or public
            broadcasts. Start interacting with other <strong class=highlighted>glowfori</strong> members.
      %tr
        %td.b-welcome__column.center= link_to 'LET\'S GO', connections_path, class: 's-btn-warning'
        %td.b-welcome__column.center= link_to 'LET\'S GO', companies_path, class: 's-btn-warning'
        %td.b-welcome__column.center= link_to 'LET\'S GO', company_path(@company), class: 's-btn-warning'            

app/views/home/home_for_unsigned.html.haml
.b-home
  .b-home-g
    .b-home-u-1
      .b-home-g-r
        .b-home-u-1-5
        .b-home-u-3-5
          .b-home__logo
            = link_to '', root_url, class: 'b-logo-big'
            %h1.b-home__slogan
              Home to the connected companies.
              %br
              Finding trusted quality partners the first time.
        .b-home-u-1-5


      .b-home-g-r
        .b-home-u-1-6
        .b-home-u-1-3
          .b-home__auth
            = link_to 'Sign up Now', new_user_registration_path, class: 's-btn-warning'
        .b-home-u-1-3
          .b-home__auth
            = link_to 'Take a Tour', walk_path, class: 's-btn-warning'
        .b-home-u-1-6

      .b-home-g-r
        .b-home-u-1-4
        .b-home-u-1-2
          %h1.b-home__slogan Available Today on Glowfori
          .s-tags
            - @tags.each_slice(4).each_with_index do |tags_block, index|
              - tags_block.each do |tag|
                = link_to tag.name, companies_url(by_tags: tag.name), class: "s-tags__tag #{tag_css_class(index)}"
        .b-home-u-1-4


= content_for(:javascript_code) do
  HomePage.init();