config/routes.rb
Glowcon::Application.routes.draw do

  devise_for :users, 
    path: '', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout'},
    controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      unlocks: "users/unlocks"
    }
  
  #devise_scope :user do
   # get 'confirm/:confirmation_token', to: 'users/confirmations#show'
  #end 
  
  resources :entries, only: [:show, :index]

  get '/archive/:month', to: 'entries#index', as: 'archive_entries'
  get '/category/:category', to: 'entries#index', as: 'category_entries'

  resources :users do
    member do
      get :following, :followers
      get :load_follows
    end
    
    collection do
      get :pitching
      post :final_step
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :email_validation

  resources :companies do
    put :update_pitch
    put :change_logo
    resources :microposts, only: [ :create, :destroy ] do
      get :load, on: :collection
    end
    resources :messages, only: [ :create ]
  end

  resources :microposts, only: [] do
    resources :comments, only: [ :create, :destroy ]
  end

  resources :contacts, only: [:new, :create]

  resources :messages, only: [ :index ] do
    collection do
      get :search
      get :load
      post :mass_sending
    end
  end

  resources :connections, only: [ :index ] do
    collection do
      get :follow
      get :load
    end
  end

  resources :tags, only: [] do
    collection do
      get :autocomplete
    end
  end

  resources :countries, only: [ :index ], controller: :location_autocomplete do
    get :states
  end

  resources :profile, only: [ :update ] do
    member do
      patch :update_pitch
      patch :change_logo
      patch :update_user_data
    end
  end

  root to: 'home#index'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/dashboard', to: 'static_pages#dashboard'
  get '/terms', to: 'static_pages#terms'
  get '/code', to: 'static_pages#code'
  get '/walk', to: 'static_pages#walk'

  get 'static_pages/final_step_design'
  get 'static_pages/create_glows'
  get 'static_pages/make_connections'
  get 'static_pages/private_messages'

  resources :m do
    collection do
      get :connections
      get :welcome
      get :dashboard
      get :home
      get :blog
      get :blog_item
      get :contacts
      get :reset
      get :sign_1
      get :sign_2
      get :sign_3
      get :profile
      get :messages
      get :followers
    end
  end
end

app/models/company.rb
require "#{Rails.root}/lib/taggable_extensions/company_relations.rb"
require "#{Rails.root}/lib/taggable_extensions/company_helpers.rb"

class Company < ActiveRecord::Base

  include TaggableExtensions::CompanyRelations
  include TaggableExtensions::CompanyHelpers
  
  POSSIBLE_SEARCH_OPS = %w{ name country state city }
  TAGS_DATA = {
    capabilities_offered: 'Capabilities you offer',
    capabilities_lookedfor: 'Capabilities you look for',
    company_certification: 'Certifications your company holds'
  }

  has_one :company_relationship
  has_one :user, through: :company_relationship

  has_many :addresses, dependent: :destroy

  has_many :glows
  has_many :messages

  accepts_nested_attributes_for :addresses

  scope :by_name, -> (name) { 
    where("lower(companies.company_name) LIKE ?", "%#{name.downcase}%")
  }

  scope :by_city, -> (city) {
    joins(:addresses).
    where("addresses.city LIKE ?", "%#{city}%")
  }

  scope :by_state, -> (state_id) {
    joins(:addresses).
    where("addresses.state_id = ?", state_id)
  }

  scope :by_country, -> (country_id) {
    joins(:addresses).
    where("addresses.country_id = ?", country_id)
  }  

  scope :by_offer_tags, -> (tags) { 
    tagged_with(tags.split(','), on: :capabilities_offered, any: true)
  }   

  scope :by_looked_tags, -> (tags) {
    tagged_with(tags.split(','), on: :capabilities_lookedfor, any: true)
  }

  scope :by_certificates, -> (tags) {
    tagged_with(tags.split(','), on: :company_certification, any: true)
  }  

  scope :not_in, -> (company) {
    where("companies.id NOT IN (?)", company.id)
  }

  scope :verified, -> {
    joins(:user).
    where("users.confirmed_at IS NOT NULL")
  }

  def addresses_attributes=(attributes)
    self.primary_address.update(attributes['0'])
  end

  def addresses_attributes=(attributes)
    self.primary_address.update_attributes(attributes['0'])
  end

  def primary_address
    addresses.first || addresses.build
  end

  has_attached_file :logo, styles: { large: '137x137#', medium: '100x60#', thumb: '50x50#' }, default_url: "logo-din-medium-black.png"
  validates_attachment :logo, size: { in: 1..2.megabytes }, content_type: { content_type: %r{^image/(?:png|jpe?g|gif)\b}i, message: 'not an image or empty file' }

  validates :company_name, presence: true, uniqueness: {case_sensitive: false}
  #validates :company_country, presence: true

  #VALID_DOMAIN = /[a-z\d\-.]+\.[a-z]+\z/i
  #validates :company_domain, format: {with: VALID_DOMAIN}, uniqueness: {case_sensitive: false}

  before_save { |company| company.company_domain = self.company_domain.downcase if self.company_domain }

  acts_as_taggable

  def self.tag_cloud_for(what, n = 30)
    tag_counts_on(what).order('count desc').limit(n).map {|x| [x.name, x.count]}
  end

  def top_capabilities(type)
    self.class.tag_counts_on(type).
      where("tags.name IN (?)", send(type + '_list')).
      order('count desc').
      map {|x| [x.name, x.count - 1]}
  end

  # capabilities, that your company offer
  def top_capabilities_wanted_right_now(glowing = nil)
    tags_offer = top_capabilities('capabilities_offered')
    if glowing == true
      tags_offer.select { |tag_block| tag_block[1] > 0 }
    elsif glowing == false
      tags_offer.select { |tag_block| tag_block[1] == 0 }
    end
  end

  # capabilities, that your company looking for
  def top_capabilities_needed_right_now(glowing = nil)
    tags_needed = top_capabilities('capabilities_lookedfor')
    if glowing == true
      tags_needed.select { |tag_block| tag_block[1] > 0 }
    elsif glowing == false
      tags_needed.select { |tag_block| tag_block[1] == 0 }
    end
  end 

  def companies_with_capailities(type)
    self.class.tag_counts_on(type).
      where("tags.name IN (?)", send(inverse_capability(type) + '_list')).
      order('count desc').
      map {|x| [x.name, x.count]}
  end

  def inverse_capability(type)
    type == 'capabilities_offered' ? 'capabilities_lookedfor' : 'capabilities_offered'
  end

  class << self
    def search(current_user, search_ops, tags_mode, tags_list)
      companies = Company.verified.not_in(current_user.company)

      search_ops.each do | k, v |
        companies = companies.send(k, v) if search_ops[k].present?
      end
      
      companies = companies.send("by_#{tags_mode}", tags_list) if tags_list.present?
      companies.includes(:addresses)
    end
  end
end

app/controllers/companies_controller.rb
require 'company_modules/search'

class CompaniesController < ApplicationController

  include CompanyModules::Search

  before_filter :save_selected_category, only: [ :index ]
  before_action :authenticate_user!, only:  [:new, :create, :index, :show, :edit, :update, :update_pitch]

  before_action :set_company, only: [:show]
  before_action :set_company_for_owner, only: [:edit, :update, :destroy]
  before_action :search_by_conditions, only: [ :index ]
  before_action :set_active_tab!, only: [ :index, :show ]
  before_action :fetch_glows, only: [ :show ]

  def index
  end

  def show
    @top_wanted_capabilities = @company.capabilities_offered.
      select("tags.name, tags.capabilities_offered_count").
      order("tags.capabilities_offered_count DESC")
    @top_certifications = @company.company_certification.
      select("tags.name, tags.company_certification_count").
      order("tags.company_certification_count DESC")
  end

  def new
    @company = Company.new
    @company_relationship = @company.build_company_relationship
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      @companyrelationship = @company.build_company_relationship(user_id: current_user.id , company_id: @company.id)
      @companyrelationship.save
      redirect_to root_url, :notice => "Congratulations, your company is now created and associated with you."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @company.update(company_params)
  end

  def update_pitch
    @company = current_user.company
    @company.update!(company_params)
  end

  def change_logo
    @company = current_user.company
    @company.update(change_logo_atts)
  end

  def destroy
  end

  private

  def fetch_glows
    microposts = if @company.id == current_user.company.id
      Micropost.followed(current_user)
    else
      @company.user.microposts.not_private
    end

    @microposts = microposts.glows.
      includes(:user, :children, to: [ :company ]).
      page(params[:page]).per(10)
  end

  def set_company
    @company = Company.verified.find(params[:id])
  end  

  def set_company_for_owner
    @company = Company.verified.readonly(false).find(params[:id])
    if @company != current_user.company
      redirect_to root_url
      return
    end
  end  

  def save_selected_category
    if !user_signed_in? && params[:by_tags].present?
      session['selected_tag_before_signin'] = params[:by_tags]
    end
  end

  def set_active_tab!
    @active_tab = params[:id].present? ? 'dashboard' : 'companies'
  end

  def pitch_params
    params.require(:company).permit(
      :company_profile
    )
  end

  def company_params
    params.require(:company).permit(
      :logo, 
      :dummy,
      :company_name, 
      :company_profile, 
      :company_mission,
      :company_services, 
      :company_website, 
      :capabilities_offered_list, 
      :capabilities_lookedfor_list,
      :company_certification_list, 
      :products_description,
      addresses_attributes: [
        :tel,
        :street,
        :city,
        :zip,
        :country_id,
        :state_id
      ]
    )
  end

  def change_logo_atts
    params.require(:company).
      permit(:logo)
  end  
end

app/helpers/companies_helper.rb
module CompaniesHelper

  def tags_list(company, search_by_tags_mode)
    method_name = case search_by_tags_mode.to_s
      when 'looked_tags'
        'capabilities_lookedfor'
      when 'certificates'
        'company_certification'
      else
        'capabilities_offered'
    end

    company.send("#{method_name}_list").join(', ')
  end

end

app/views/companies/edit_blocks/_are_your_sure_modal.html.haml
.are_your_sure_modal
  %p
    Your changes have not been saved!
  %div
    %input.s-btn#fancyConfirm_cancel{ type: 'button', value: 'Cancel' }
    %input.s-btn.pull-left#fancyConfirm_ok{ type: 'button', value: 'Yes, I understand' }

app/views/companies/edit_blocks/_base_data.html.haml
.b-profile__content#company_base_data
  .b-profile__title Company Profile
  / .b-profile__subtitle General

  = render 'companies/edit_blocks/change_logo', company: current_user.company

  = form_for(current_user.company, url: profile_path(current_user.company), method: :patch, html: { class: 'b-form' }, remote: true) do |f|
    = render 'shared/error_messages', object: f.object
    = hidden_field_tag :from, :base_data


    = f.fields_for :addresses, @company.primary_address do |a|

      %p
        = a.label :company_name, 'Company Name', class: 's-single-label'
        = f.text_field :company_name, class: 's-input'
      %p
        = a.label :street, 'Street', class: 's-single-label'
        = a.text_field :street, class: 's-input'
      %p
        = a.label :city, 'City', class: 's-single-label'
        = a.text_field :city, class: 's-input'
      %p
        = a.label :zip, 'Postal Code / Zip', class: 's-single-label'
        = a.text_field :zip, class: 's-input'
      %p
        = a.label :state_id, 'State', class: 's-single-label'
        = text_field_tag :state_id, ( a.object.state.present? ? a.object.state.name : '' ), class: 's-input'
        = a.hidden_field :state_id, id: 'company_state_id'
      %p
        = a.label :country_id, 'Country', class: 's-single-label'
        = text_field_tag :country_id, ( a.object.country.present? ? a.object.country.name : '' ), class: 's-input'
        = a.hidden_field :country_id, id: 'company_country_id'
      %p
        = a.label :tel, 'Telephone', class: 's-single-label'
        %span{ class: 'company_tel_prefix pull-left' }
          = a.object.country.try(:phone_prefix)
        = a.text_field :tel, id: 'company_tel', class: 's-input'
      %p
        = a.label :company_website, 'Web Site', class: 's-single-label'
        = f.text_field :company_website, class: 's-input'
   
    = render 'companies/edit_blocks/submit_block'

app/views/companies/edit_blocks/_change_logo.html.haml
= form_for company, url: change_logo_profile_path(company), html: { class: "file-field-container", multipart: true, method: :patch }, remote: true, authenticity_token: true do |f|

  = f.label :logo, 'Company Logo', class: 's-single-label'
  = f.file_field :logo, size: 2, class: 'hidden'
  .b-company-logo
    .b-company-logo__image
      = image_tag company.logo.url(:large)
    .b-company-logo__tools
      %button.s-btn.js-file-emulator Browse
      .b-company-logo__text * jpg, jpeg, png, gif only (less than 2MB)
    %span.upload_error_message.hidden.pull-left
    .company-progress-bar-container.pull-left   

app/views/companies/edit_blocks/_marketing_intellegence.html.haml
.b-profile__content#company_marketing{ class: 'current' }
  .b-profile__title Market Data
  / .b-profile__subtitle Marketing Intelligence

  = form_for(current_user.company, url: profile_path(current_user.company), method: :patch, html: { class: 'b-form' }, remote: true) do |f|
    = hidden_field_tag :from, :marketing

    - Company::TAGS_DATA.each do | tags_block_name, placeholder |
      .b-tags_block
        = f.label "#{tags_block_name}_list", placeholder, class: 's-single-label'
        = hidden_field_tag "#{tags_block_name}_default_list", f.object.send("#{tags_block_name}_list").join(', ')
        .tag_autocomplete_block
          = f.hidden_field "#{tags_block_name}_list", value: f.object.send("#{tags_block_name}_list").join(', '), class: 'hidden_tags_input'
          .js-edit_tags_container
            = render 'tag_blocks/edit_item', tags_block_name: tags_block_name

    = render 'companies/edit_blocks/submit_block'

app/views/companies/edit_blocks/_navigation.html.haml
.b-profile__sidebar
  %ul.b-sidebar-menu
    %li.b-sidebar-menu__item
      = link_to 'User Data', '#', class: "b-sidebar-menu__link", data: { content: 'company_user_data' }
    %li.b-sidebar-menu__item
      = link_to 'Company Data', '#', class: "b-sidebar-menu__link", data: { content: 'company_base_data' }
    %li.b-sidebar-menu__item
      = link_to 'Market Data', '#', class: "b-sidebar-menu__link current", data: { content: 'company_marketing' }
    %li.b-sidebar-menu__item
      = link_to 'Company Services', '#', class: "b-sidebar-menu__link", data: { content: 'company_services' }

app/views/companies/edit_blocks/_services.html.haml
.b-profile__content#company_services
  .b-profile__title Company Profile
  / .b-profile__subtitle Services

  = form_for(current_user.company, url: profile_path(current_user.company), method: :patch, html: { class: 'b-form' }, remote: true) do |f|
    = hidden_field_tag :from, :services

    .company_services_block
      = f.label :company_profile, "elevator pitch", class: 's-single-label'
      .s-textarea
        = f.text_area :company_profile, rows: 4  
      .company_textarea_hint.pull-right.countdown{ data: { limit: 250 } } 250 Characters remaining
    .company_services_block
      = f.label :company_mission, "what we do", class: 's-single-label'  
      .s-textarea
        = f.text_area :company_mission, rows: 4
      .company_textarea_hint.pull-right.countdown{ data: { limit: 2000 } } 2000 Characters remaining  
    .company_services_block
      = f.label :company_services, "products & services", class: 's-single-label'
      .s-textarea
        = f.text_area :company_services, rows: 4 
      .company_textarea_hint.pull-right.countdown{ data: { limit: 2000 } } 2000 Characters remaining
    / .company_services_block
    /   = f.label :products_description, "Describe your products", class: 's-single-label'
    /   .s-textarea
    /     = f.text_area :products_description, rows: 4
    /   .company_textarea_hint.pull-right.countdown{ data: { limit: 2000 } } 2000 Characters remaining  

    = render 'companies/edit_blocks/submit_block'

app/views/companies/edit_blocks/_submit_block.html.haml
.clear_with_50
.error_message.pull-right
  There are some errors!
.success_message.pull-right
  Updated successfully!
%button.b-profile__submit.s-btn Save
= image_tag 'spinner.gif', class: 'loading_spinner pull-right'

app/views/companies/edit_blocks/_user_data.html.haml
.b-profile__content#company_user_data
  .b-profile__title User Data
  .b-profile__subtitle

  = form_for(current_user, url: update_user_data_profile_url(current_user), method: :patch, html: { class: 'b-form' }, remote: true) do |f|
    = hidden_field_tag :from, :user_data

    -#    .gravatar_block
      %label{ class: "s-single-label" } Avatar
      .b-company-logo
        .b-company-logo__image
          = gravatar_for current_user, size: 137
        .b-company-logo__tools
          = link_to 'Change', 'http://gravatar.com/emails', 'data-popup' => true, class: 's-btn'

    .fields_container
      = render 'profile/user_data_fields'

    = render 'companies/edit_blocks/submit_block'